# Generated by Django 3.1.5 on 2021-05-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='title',
            new_name='name',
        ),
    ]
