# Generated by Django 3.1.5 on 2021-05-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0003_alter_taskgroup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
