# Generated by Django 3.1.5 on 2021-05-17 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_group', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayPlagiarism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay1', models.IntegerField(null=True)),
                ('essay2', models.IntegerField(null=True)),
                ('plagiarism', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('task_group', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='task_group.taskgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=9000)),
                ('date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='authors.author')),
                ('task_group', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='task_group.taskgroup')),
            ],
        ),
    ]
