# Generated by Django 3.1.5 on 2021-05-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0001_initial'),
        ('authors', '0001_initial'),
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='author',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='authors.author'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='task_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='task_group.taskgroup'),
        ),
        migrations.AlterField(
            model_name='essayplagiarism',
            name='task_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='task_group.taskgroup'),
        ),
    ]
