# Generated by Django 3.1.5 on 2021-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_alter_essay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
