# Generated by Django 3.2 on 2021-05-10 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20210509_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='EssayPlagiarism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essayAVG', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date', models.DateField()),
                ('essays', models.ManyToManyField(to='essays.Essay')),
            ],
        ),
    ]
