# Generated by Django 3.2 on 2021-05-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20210518_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
