# Generated by Django 3.2 on 2021-05-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_group', '0003_alter_taskgroup_id'),
        ('essays', '0004_auto_20210510_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='task_group',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='task_group.taskgroup'),
        ),
    ]
