# Generated by Django 3.1.5 on 2021-05-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_auto_20210518_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='essayplagiarism',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='essayplagiarism',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
