# Generated by Django 3.2 on 2021-05-16 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_essay_task_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=9000),
        ),
    ]
