# Generated by Django 3.2 on 2021-05-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0006_alter_essay_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='content',
            field=models.CharField(max_length=9000),
        ),
    ]
